-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."DimDate"
(
    dateid bigint NOT NULL,
    date date,
    year bigint,
    quarter bigint,
    quartername character varying,
    month bigint,
    monthname character varying,
    day bigint,
    weekday bigint,
    weekdayname character varying,
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."DimCategory"
(
    categoryid bigint NOT NULL,
    category character varying,
    PRIMARY KEY (categoryid)
);

CREATE TABLE IF NOT EXISTS public."DimItem"
(
    itemid bigint NOT NULL,
    item character varying,
    PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS public."DimCountry"
(
    countryid bigint NOT NULL,
    country character varying,
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS public."FactSales"
(
    orderid bigint NOT NULL,
    dateid bigint,
    countryid bigint,
    categoryid bigint,
    amount bigint,
    PRIMARY KEY (orderid)
);

ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES public."DimItem" (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."DimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."DimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (categoryid)
    REFERENCES public."DimCategory" (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;